### ISSUE TITLE
Getting an error "TypeError: 'module' object is not callable"

### ISSUE THREAD

**Issue by mady143** [prashil2792/Question-Answering-System-Deep-Learning#3]
HI @prashil2792 ,

I am using your model when i am trying to execute the memorynetwork.py i am geting an error **"TypeError: 'module' object is not callable"**,
Could you help in this to resolve the issue..

Thanks and Regards,
Manikantha Sekhar.

Happy Codding...

**Comment by AkashBondarde1122** [comment]
hi @mady143  Have you figured out the error ?

Thanks and Regards,
Akash

**Comment by CodingBeast99** [comment]
Even i'm Getting the same error.and that error is because we are using something which is not imported properly.

Thanks & Regards,
Prudhvi kari

**Comment by CodingBeast99** [comment]
Finally Solved this issue .This was issue due to merge layer in keras. Solved by Using other layers .
For the code visit my profile.


Thanks & Regards,
Prudhvi Kari

**Comment by mmusunur** [comment]
hi @AkashBondarde1122  no i didn't resolve that issue if you did it can you tell me how to overcome with the perfect solution

Thanks and Regards,
Manikantha Sekhar

**Comment by mmusunur** [comment]
Hi @AkashBondarde1122 @CodingBeast99 @prashil2792 ,
I resolved this issue by downgrading the keras version to 2.0.5 so this help me to work on further training process to generate a model.

Thanks & Regards,
Manikantha Sekhar

**Comment by prashil2792** [comment]
Hi @mady143 @AkashBondarde1122 @CodingBeast99 
Thanks for pointing out this issue. I have updated the code in py file and jupyter notebook as well. It happened due to change in keras API.

Let me know if you're still facing issues.
