### ISSUE TITLE
while adding custom user and story input giving error

### ISSUE THREAD

**Issue by e-turk** [prashil2792/Question-Answering-System-Deep-Learning#4]
I have a memory network task that I am working on RNN LSTM networks. I have your Python codes in order to train network with bAbI dataset and get results. For testing network, adding custom story and query to the network but having this error:
memn2n.py", line 57, in x = [word_idx[w] for w in story]
or this error
ValueError: too many values to unpack (expected 3)
or this error
 y[word_idx[answer]] = 1

KeyError: '.'

**Comment by prashil2792** [comment]
Hi @e-turk 
Can you share screenshot of your code of custom story along with the error ?
